AllCops:
  TargetRubyVersion: 2.3.1

Metrics/MethodLength:
  CountComments: false
  Max: 15

Metrics/AbcSize:
  Max: 18

Metrics/LineLength:
  Max: 100

Layout/TrailingWhitespace:
  Enabled: false

Layout/SpaceInsideArrayPercentLiteral:
  Enabled: false

Layout/AlignArray:
  Enabled: false

Style/StringLiterals:
  Enabled: false